name: Github Pages

on:
  push:
    branches: [feature/version-documentation]

jobs:
  getTags:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/kherp/react-components/tags
          owner: octokit
          repo: request-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: set-matrix
        run: |
          arr=( $(echo $data | jq -r '.[].name') )
          JSON="{\"include\":["
          minver="v3.0.0"
          for i in "${arr[@]}"
          do
            if [ "$(printf '%s\n' "$minver" "$i" | sort -V | head -n1)" = "$minver" ]; then 
              JSON="$JSON$(printf '{"name": "%s"}, ' "${i}")"
            fi
          done
          # JSON="$JSON$(printf '{"name": "%s"}, ' "${arr[@]}" | sed '$s/,$//')"
          JSON="${JSON%,*} ${JSON##*,}"
          JSON="$JSON]}"
          echo "test: $JSON"
          echo "::set-output name=matrix::$JSON"
        env:
          data: ${{steps.get_latest_release.outputs.data}}
  buildDocs:
    needs: getTags
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix: ${{fromJson(needs.getTags.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.name }}
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Installing dependencies
        run: npm ci
      - name: Building docs
        id: get_doc_folder
        run: |
          requiredver="v5.0.0"
          currentver=$(echo ${{ matrix.name }})
          if [ "$(printf '%s\n' "$requiredver" "$currentver" | sort -V | head -n1)" = "$requiredver" ]; then 
            echo "base=\"/react-components/${currentver}\"" >> .env
            npm run build:docs
            echo "::set-output name=doc_folder::docs/public"
          else
            npm run docs
            echo "::set-output name=doc_folder::docs"
          fi
      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: ${{steps.get_doc_folder.outputs.doc_folder}} # The folder the action should deploy.
          TARGET_FOLDER: ${{ matrix.name }}
          CLEAN: true # Automatically remove deleted files from the deploy branch
          CLEAN_EXCLUDE: '["version"]'
  # gh_pages:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Setup Node
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: 14.x

  #     - name: Installing dependencies
  #       run: npm ci

  #     - name: Building docs
  #       run: npm run build:docs

  #     - name: Publish
  #       uses: crazy-max/ghaction-github-pages@v2.2.0
  #       with:
  #         build_dir: docs/public
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          