name: Github Pages

on:
  push:
    branches: [feature/version-documentation]

jobs:
  getTags:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/kherp/react-components/tags
          owner: octokit
          repo: request-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: set-matrix
        run: |
          arr=( $(echo $data | jq -r '.[].name') )
          JSON="{\"include\":["
          # for k in "${arr[@]}" do
          #   JSON="$JSON{\"name\": \"\"},"
          # done
          JSON="$JSON$(printf '{"name": "%s"}, ' "${arr[@]}" | sed '$s/,$//')"
          JSON="${JSON%,*} ${JSON##*,}"
          JSON="$JSON]}"
          echo "test: $JSON"
          echo "::set-output name=matrix::$JSON"
        env:
          data: ${{steps.get_latest_release.outputs.data}}
  buildDocs:
    needs: getTags
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.getTags.outputs.matrix)}}
    steps:
      - run: |
        requiredver="v5.0.0"
        currentver={{$matrix.name}}
        echo $requiredver
        echo $currentver
        if [ "$(printf '%s\n' "$requiredver" "$currentver" | sort -V | head -n1)" = "$requiredver" ]; then 
                echo "greater than or equal to ${requiredver}"
        else
                echo "less than ${requiredver}"
        fi
  # gh_pages:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Setup Node
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: 14.x

  #     - name: Installing dependencies
  #       run: npm ci

  #     - name: Building docs
  #       run: npm run build:docs

  #     - name: Publish
  #       uses: crazy-max/ghaction-github-pages@v2.2.0
  #       with:
  #         build_dir: docs/public
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          